
package application;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import login.Login;

public class ComputeE extends javax.swing.JFrame {

    /**
     * Creates new form ComputeE
     */
    public ComputeE() {
        initComponents();
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:C:/Users/"+Login.user+"/Documents/Databases/ApartmentsManagement.db");
            Statement st = conn.createStatement();
            ResultSet rec = st.executeQuery("SELECT ID FROM ApartmentsBuilding");
            while (rec.next()) {
                jComboBox1.addItem(rec.getString(1));
            }
        } catch (SQLException s) {

        } catch (Exception e) {

        }
        for (int i = 2000; i <= 2018; i++) {
            jComboBox3.addItem("" + i);
        }

        jComboBox4.addItem("Ιανουάριος");
        jComboBox4.addItem("Φεβρουάριος");
        jComboBox4.addItem("Μάρτιος");
        jComboBox4.addItem("Απρίλιος");
        jComboBox4.addItem("Μάϊος");
        jComboBox4.addItem("Ιούνιος");
        jComboBox4.addItem("Ιούλιος");
        jComboBox4.addItem("Αύγουστος");
        jComboBox4.addItem("Σεπτέμβριος");
        jComboBox4.addItem("Οκτώβριος");
        jComboBox4.addItem("Νοέμβριος");
        jComboBox4.addItem("Δεκέμβριος");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setBackground(new java.awt.Color(102, 102, 255));
        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Επιλέξτε πολυκατοικία" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setBackground(new java.awt.Color(102, 102, 255));
        jComboBox2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Επιλέξτε διαμέρισμα" }));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Υπολογισμός κοινοχρήστων");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel1.setText("Πολυκατοικία");

        jLabel2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel2.setText("Διαμέρισμα");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("ΚΟΙΝΟΧΡΗΣΤΑ:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Ρεύμα:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Νερό:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Καθαρίστρια:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Διάφορα έξοδα:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("ΘΕΡΜΑΝΣΗ:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Αξία θέρμανσης:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Συντήρηση καυστήρα:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("ΣΥΝΙΔΙΟΚΤΗΣΙΑ:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("ΕΕΤΗΔΕ:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Αλλαγή πόρτας κ.λπ.:");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("ΑΝΕΛΚΥΣΤΗΡΑΣ:");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Έξοδα συντήρησης ανελκυστήρα:");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Έξοδα ανταλλακτικών για τον ανελκυστήρα:");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Έξοδα τεχνικών:");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("ΣΥΝΟΛΟ:");

        jTextField1.setEditable(false);

        jTextField2.setEditable(false);

        jTextField3.setEditable(false);

        jTextField4.setEditable(false);

        jTextField5.setEditable(false);

        jTextField6.setEditable(false);

        jTextField7.setEditable(false);

        jTextField8.setEditable(false);

        jTextField9.setEditable(false);

        jTextField10.setEditable(false);

        jTextField11.setEditable(false);

        jTextField12.setEditable(false);

        jTextField13.setEditable(false);

        jTextField14.setEditable(false);

        jTextField15.setEditable(false);

        jTextField16.setEditable(false);

        jTextField17.setEditable(false);

        jTextField18.setEditable(false);

        jTextField19.setEditable(false);

        jTextField20.setEditable(false);

        jTextField21.setEditable(false);

        jTextField22.setEditable(false);

        jTextField23.setEditable(false);

        jTextField24.setEditable(false);

        jTextField25.setEditable(false);

        jTextField26.setEditable(false);

        jTextField27.setEditable(false);

        jTextField28.setEditable(false);

        jTextField29.setEditable(false);

        jTextField30.setEditable(false);

        jTextField33.setEditable(false);

        jTextField34.setEditable(false);

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Πίσω");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox3.setBackground(new java.awt.Color(102, 102, 255));
        jComboBox3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Επιλέξτε έτος" }));

        jComboBox4.setBackground(new java.awt.Color(102, 102, 255));
        jComboBox4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Επιλέξτε μήνα" }));

        jButton4.setBackground(new java.awt.Color(102, 102, 255));
        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Εξαγωγή Απόδειξης");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel13)))
                                        .addComponent(jLabel8)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)))
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField16)
                                .addComponent(jTextField15)
                                .addComponent(jTextField14)
                                .addComponent(jTextField13)
                                .addComponent(jTextField12)
                                .addComponent(jTextField11)
                                .addComponent(jTextField10)
                                .addComponent(jTextField9)
                                .addComponent(jTextField8)
                                .addComponent(jTextField7)
                                .addComponent(jTextField6)
                                .addComponent(jTextField5)
                                .addComponent(jTextField4)
                                .addComponent(jTextField3)
                                .addComponent(jTextField1)
                                .addComponent(jTextField2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(547, 547, 547)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField34)
                    .addComponent(jTextField33, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField30)
                    .addComponent(jTextField29)
                    .addComponent(jTextField28)
                    .addComponent(jTextField27)
                    .addComponent(jTextField26)
                    .addComponent(jTextField25)
                    .addComponent(jTextField24)
                    .addComponent(jTextField23)
                    .addComponent(jTextField22)
                    .addComponent(jTextField21)
                    .addComponent(jTextField20)
                    .addComponent(jTextField18)
                    .addComponent(jTextField17)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField19, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(8, 8, 8)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jComboBox1.getSelectedItem().toString().equals("Επιλέξτε πολυκατοικία") || jComboBox2.getSelectedItem().toString().equals("Επιλέξτε διαμέρισμα") || jComboBox3.getSelectedItem().toString().equals("Επιλέξτε έτος") || jComboBox4.getSelectedItem().toString().equals("Επιλέξτε μήνα")) {
            JOptionPane.showMessageDialog(null, "Δεν έχετε επιλέξει τα στοιχεία της πολυκατοικίας!", "Λάθος", JOptionPane.ERROR_MESSAGE);
        } else {
            float ml = 0;
            float e = 0, k = 0, k1 = 0, k2 = 0, k3 = 0, k4 = 0, th = 0, th1 = 0, th2 = 0, s = 0, s1 = 0, s2 = 0, a = 0, a1 = 0, a2 = 0, a3 = 0;
            String se, sk, sk1, sk2, sk3, sk4, sth, sth1, sth2, ss, ss1, ss2, sa, sa1, sa2, sa3;

            jTextField1.setText("0");
            jTextField2.setText("0");
            jTextField3.setText("0");
            jTextField4.setText("0");
            jTextField5.setText("0");

            jTextField16.setText("0");

            jTextField6.setText("0");
            jTextField7.setText("0");
            jTextField8.setText("0");

            jTextField9.setText("0");
            jTextField10.setText("0");
            jTextField11.setText("0");

            jTextField12.setText("0");
            jTextField13.setText("0");
            jTextField14.setText("0");
            jTextField15.setText("0");

            try {
                Class.forName("org.sqlite.JDBC");
                Connection conn = DriverManager.getConnection("jdbc:sqlite:C:/Users/"+Login.user+"/Documents/Databases/ApartmentsManagement.db");

                Statement st = conn.createStatement();
                Statement st0 = conn.createStatement();
                Statement st1 = conn.createStatement();
                Statement st2 = conn.createStatement();
                Statement st3 = conn.createStatement();
                Statement st4 = conn.createStatement();

                ResultSet rec, rec0, rec1, rec2, rec3, rec4;

                rec0 = st0.executeQuery("SELECT TotalCosts FROM Expenses WHERE BuildingID=" + jComboBox1.getSelectedItem().toString()
                        + " AND DateYear=" + jComboBox3.getSelectedItem().toString()
                        + " AND DateMonth='" + jComboBox4.getSelectedItem().toString() + "'"
                );

                rec1 = st1.executeQuery("SELECT TotalCosts,Electricity,Water,Cleaning,OtherExpenses from SharedUtilityBills where BuildingID=" + jComboBox1.getSelectedItem().toString()
                        + " AND DateYear=" + jComboBox3.getSelectedItem().toString()
                        + " AND DateMonth='" + jComboBox4.getSelectedItem().toString() + "'"
                );

                rec2 = st2.executeQuery("SELECT TotalCosts,ValueOfHeating,BurnerMaintenance FROM Heating WHERE BuildingID=" + jComboBox1.getSelectedItem().toString()
                        + " AND DateYear=" + jComboBox3.getSelectedItem().toString()
                        + " AND DateMonth='" + jComboBox4.getSelectedItem().toString() + "'"
                );

                rec3 = st3.executeQuery("SELECT TotalCosts,ESFESS,OtherCosts FROM JointOwnerShip where BuildingID=" + jComboBox1.getSelectedItem().toString()
                        + " AND DateYear=" + jComboBox3.getSelectedItem().toString()
                        + " AND DateMonth='" + jComboBox4.getSelectedItem().toString() + "'"
                );

                rec4 = st4.executeQuery("SELECT TotalCosts,ElevatorMaintenanceCosts,SparePartsCosts,TechnicalCosts FROM Elevator WHERE BuildingID=" + jComboBox1.getSelectedItem().toString()
                        + " AND DateYear=" + jComboBox3.getSelectedItem().toString()
                        + " AND DateMonth='" + jComboBox4.getSelectedItem().toString() + "'"
                );

                if (rec0.next()) {
                    e = rec0.getFloat(1);
                    jTextField16.setText(rec0.getString(1));
                } else {
                    JOptionPane.showMessageDialog(null, "Δεν έχουν καταγραφεί έξοδα για τα συγκεκριμένα στοιχεία!", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                while (rec1.next()) {
                    k = rec1.getFloat(1);
                    k1 = rec1.getFloat(2);
                    k2 = rec1.getFloat(3);
                    k3 = rec1.getFloat(4);
                    k4 = rec1.getFloat(5);
                    jTextField1.setText(rec1.getString(1));
                    jTextField2.setText(rec1.getString(2));
                    jTextField3.setText(rec1.getString(3));
                    jTextField4.setText(rec1.getString(4));
                    jTextField5.setText(rec1.getString(5));
                }
                while (rec2.next()) {
                    th = rec2.getFloat(1);
                    th1 = rec2.getFloat(2);
                    th2 = rec2.getFloat(3);
                    jTextField6.setText(rec2.getString(1));
                    jTextField7.setText(rec2.getString(2));
                    jTextField8.setText(rec2.getString(3));
                }
                while (rec3.next()) {
                    s = rec3.getFloat(1);
                    s1 = rec3.getFloat(2);
                    s2 = rec3.getFloat(3);
                    jTextField9.setText(rec3.getString(1));
                    jTextField10.setText(rec3.getString(2));
                    jTextField11.setText(rec3.getString(3));
                }
                while (rec4.next()) {
                    a = rec4.getFloat(1);
                    a1 = rec4.getFloat(2);
                    a2 = rec4.getFloat(3);
                    a3 = rec4.getFloat(4);
                    jTextField12.setText(rec4.getString(1));
                    jTextField13.setText(rec4.getString(2));
                    jTextField14.setText(rec4.getString(3));
                    jTextField15.setText(rec4.getString(4));
                }

                rec = st.executeQuery("SELECT Millimeters FROM Apartment WHERE BuildingID=" + jComboBox1.getSelectedItem().toString()
                        + " AND ID='" + jComboBox2.getSelectedItem().toString() + "'");

                while (rec.next()) {
                    ml = rec.getFloat(1);
                }

                e = ml * e;

                k = ml * k;
                k1 = ml * k1;
                k2 = ml * k2;
                k3 = ml * k3;
                k4 = ml * k4;

                th = ml * th;
                th1 = ml * th1;
                th2 = ml * th2;

                s = ml * s;
                s1 = ml * s1;
                s2 = ml * s2;

                a = ml * a;
                a1 = ml * a1;
                a2 = ml * a2;
                a3 = ml * a3;

                se = String.format("%.02f", e);

                sk = String.format("%.02f", k);
                sk1 = String.format("%.02f", k1);
                sk2 = String.format("%.02f", k2);
                sk3 = String.format("%.02f", k3);
                sk4 = String.format("%.02f", k4);

                sth = String.format("%.02f", th);
                sth1 = String.format("%.02f", th1);
                sth2 = String.format("%.02f", th2);

                ss = String.format("%.02f", s);
                ss1 = String.format("%.02f", s1);
                ss2 = String.format("%.02f", s2);

                sa = String.format("%.02f", a);
                sa1 = String.format("%.02f", a1);
                sa2 = String.format("%.02f", a2);
                sa3 = String.format("%.02f", a3);

                jTextField34.setText(se);

                jTextField17.setText(sk);
                jTextField18.setText(sk1);
                jTextField19.setText(sk2);
                jTextField20.setText(sk3);
                jTextField21.setText(sk4);

                jTextField22.setText(sth);
                jTextField23.setText(sth1);
                jTextField24.setText(sth2);

                jTextField25.setText(ss);
                jTextField26.setText(ss1);
                jTextField27.setText(ss2);

                jTextField28.setText(sa);
                jTextField29.setText(sa1);
                jTextField30.setText(sa2);
                jTextField33.setText(sa3);

                st.close();
                st0.close();
                st1.close();
                st2.close();
                st3.close();
                st4.close();
            } catch (SQLException sql) {
                JOptionPane.showMessageDialog(null, "Κάποιο λάθος έγινε. Ελέγξτε ξανά τα στοιχεία!", "SQLException ERROR", JOptionPane.ERROR_MESSAGE);
            } catch (Exception exp) {
                JOptionPane.showMessageDialog(null, "Κάποιο λάθος έγινε. Ελέγξτε ξανά τα στοιχεία!", "Exception ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (!jComboBox1.getSelectedItem().toString().equals("Επιλέξτε πολυκατοικία")) {
            jComboBox2.removeAllItems();
            jComboBox2.addItem("Επιλέξτε διαμέρισμα");

            try {
                Class.forName("org.sqlite.JDBC");
                Connection conn = DriverManager.getConnection("jdbc:sqlite:C:/Users/"+Login.user+"/Documents/Databases/ApartmentsManagement.db");
                Statement st = conn.createStatement();
                ResultSet rec = st.executeQuery("SELECT ID FROM Apartment WHERE BuildingID=" + jComboBox1.getSelectedItem().toString());
                while (rec.next()) {
                    jComboBox2.addItem(rec.getString(1));
                }
            } catch (SQLException s) {

            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jComboBox1.getSelectedItem().toString().equals("Επιλέξτε πολυκατοικία") || jComboBox2.getSelectedItem().toString().equals("Επιλέξτε διαμέρισμα") || jComboBox3.getSelectedItem().toString().equals("Επιλέξτε έτος") || jComboBox4.getSelectedItem().toString().equals("Επιλέξτε μήνα")) {
            JOptionPane.showMessageDialog(null, "Δεν έχετε επιλέξει τα στοιχεία της πολυκατοικίας!", "Λάθος", JOptionPane.ERROR_MESSAGE);
        } else {
            String name = "";
            float ml = 0, total = 0, totalK = 0, totalTH = 0, totalS = 0, totalA = 0;
            String t = "", tK = "", tTH = "", tS = "", tA = "";

            try {
                Class.forName("org.sqlite.JDBC");
                Connection conn = DriverManager.getConnection("jdbc:sqlite:C:/Users/"+Login.user+"/Documents/Databases/ApartmentsManagement.db");
                
                Statement st = conn.createStatement();
                Statement st0 = conn.createStatement();
                Statement st1 = conn.createStatement();
                Statement st2 = conn.createStatement();
                Statement st3 = conn.createStatement();
                Statement st4 = conn.createStatement();

                Statement stf = conn.createStatement();

                ResultSet rec = st.executeQuery("SELECT OwnerName FROM Apartment WHERE BuildingID=" + jComboBox1.getSelectedItem().toString() + " AND ID='" + jComboBox2.getSelectedItem().toString() + "'");

                ResultSet rec0 = st0.executeQuery("SELECT TotalCosts FROM Expenses WHERE BuildingID=" + jComboBox1.getSelectedItem().toString()
                        + " AND DateYear=" + jComboBox3.getSelectedItem().toString()
                        + " AND DateMonth='" + jComboBox4.getSelectedItem().toString() + "'");

                ResultSet rec1 = st1.executeQuery("SELECT TotalCosts FROM SharedUtilityBills WHERE BuildingID=" + jComboBox1.getSelectedItem().toString()
                        + " AND DateYear=" + jComboBox3.getSelectedItem().toString()
                        + " AND DateMonth='" + jComboBox4.getSelectedItem().toString() + "'");

                ResultSet rec2 = st2.executeQuery("SELECT TotalCosts FROM Heating WHERE BuildingID=" + jComboBox1.getSelectedItem().toString()
                        + " AND DateYear=" + jComboBox3.getSelectedItem().toString()
                        + " AND DateMonth='" + jComboBox4.getSelectedItem().toString() + "'");

                ResultSet rec3 = st3.executeQuery("SELECT TotalCosts FROM JointOwnerShip WHERE BuildingID=" + jComboBox1.getSelectedItem().toString()
                        + " AND DateYear=" + jComboBox3.getSelectedItem().toString()
                        + " AND DateMonth='" + jComboBox4.getSelectedItem().toString() + "'");

                ResultSet rec4 = st4.executeQuery("SELECT TotalCosts FROM Elevator WHERE BuildingID=" + jComboBox1.getSelectedItem().toString()
                        + " AND DateYear=" + jComboBox3.getSelectedItem().toString()
                        + " AND DateMonth='" + jComboBox4.getSelectedItem().toString() + "'");

                ResultSet recf = stf.executeQuery("SELECT Millimeters FROM Apartment WHERE BuildingID=" + jComboBox1.getSelectedItem().toString()
                        + " AND ID='" + jComboBox2.getSelectedItem().toString() + "'");

                while (rec.next()) {
                    name = rec.getString(1);
                }
                while (rec0.next()) {
                    total = rec0.getFloat(1);
                }
                while (rec1.next()) {
                    totalK = rec1.getFloat(1);
                }
                while (rec2.next()) {
                    totalTH = rec2.getFloat(1);
                }
                while (rec3.next()) {
                    totalS = rec3.getFloat(1);
                }
                while (rec4.next()) {
                    totalA = rec4.getFloat(1);
                }

                while (recf.next()) {
                    ml = recf.getFloat(1);
                }

                total = ml * total;
                totalK = ml * totalK;
                totalTH = ml * totalTH;
                totalS = ml * totalS;
                totalA = ml * totalA;

                t = String.format("%.02f", total);
                tK = String.format("%.02f", totalK);
                tTH = String.format("%.02f", totalTH);
                tS = String.format("%.02f", totalS);
                tA = String.format("%.02f", totalA);

                st.close();
                st0.close();
                st1.close();
                st2.close();
                st3.close();
                st4.close();
                stf.close();

                if (total != 0) {
                    try {
                        Document doc = new Document();

                        try {
                            PdfWriter.getInstance(doc, new FileOutputStream("C:/Users/"+Login.user+"/Documents/Receipts/receipt-" + jComboBox1.getSelectedItem().toString() + "-"
                                    + jComboBox2.getSelectedItem().toString() + "-"
                                    + jComboBox4.getSelectedItem().toString() + "-"
                                    + jComboBox3.getSelectedItem().toString()
                                    + ".pdf"));
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(ComputeE.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        doc.open();

                        Font f = FontFactory.getFont("C:/Users/"+Login.user+"/Documents/Fonts/arial-unicode-ms/ARIALUNI.TTF", BaseFont.IDENTITY_H, BaseFont.EMBEDDED, 12);
                        Paragraph p1 = new Paragraph(new Paragraph("ΑΠΟΔΕΙΞΗ ΠΛΗΡΩΜΗΣ ΚΟΙΝΟΧΡΗΣΤΩΝ", f));
                        p1.setAlignment(Element.ALIGN_CENTER);
                        Paragraph p2 = new Paragraph(jComboBox4.getSelectedItem().toString() + "/" + jComboBox3.getSelectedItem().toString(), f);
                        p2.setAlignment(Element.ALIGN_CENTER);

                        doc.add(p1);
                        doc.add(p2);
                        doc.add(new Paragraph("\n", f));
                        doc.add(new Paragraph("\n", f));

                        doc.add(new Paragraph("Ο ιδιοκτήτης του διαμερίσματος " + jComboBox2.getSelectedItem().toString() + " της πολυκατοικίας με κωδικό " + jComboBox1.getSelectedItem().toString() + ", " + name + ", έχει "
                                + "πληρώσει τα ακόλουθα ποσά:", f));

                        doc.add(new Paragraph("\n", f));
                        doc.add(new Paragraph("ΚΟΙΝΟΧΡΗΣΤΑ:     " + tK + " ΕΥΡΩ", f));
                        doc.add(new Paragraph("ΘΕΡΜΑΝΣΗ:     " + tTH + " ΕΥΡΩ", f));
                        doc.add(new Paragraph("ΣΥΝΙΔΙΟΚΤΗΣΙΑ:     " + tS + " ΕΥΡΩ", f));
                        doc.add(new Paragraph("ΕΞΟΔΑ ΑΝΕΛΚΥΣΤΗΡΑ:     " + tA + " ΕΥΡΩ", f));
                        doc.add(new Paragraph("\n", f));
                        doc.add(new Paragraph("ΣΥΝΟΛΟ:     " + t + " ΕΥΡΩ", f));

                        doc.close();

                        JOptionPane.showMessageDialog(null, "Η εξαγωγή απόδειξης ολοκληρώθηκε!", "Completed", JOptionPane.PLAIN_MESSAGE);
                    } catch (DocumentException ex) {
                        Logger.getLogger(ComputeE.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Δεν μπορείς να εξάγεις απόδειξη αφού δεν έχουν καταγραφεί έξοδα!", "ERROR", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException s) {
                JOptionPane.showMessageDialog(null, "Κάποιο λάθος έγινε. Ελέγξτε ξανά τα στοιχεία!", "SQLException ERROR", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Κάποιο λάθος έγινε. Ελέγξτε ξανά τα στοιχεία!", "Exception ERROR", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputeE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputeE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputeE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputeE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputeE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
